### ISSUE TITLE
Visualization of non-redundant streams to other interface

### ISSUE THREAD

**Issue by scrmea** [christophe-calmejane/Hive#100]
Hello,
I have an entity that supports redundancy, however I am not using redundancy for the incoming stream. I do use redundancy on the outgoing stream.

When I open Hive on the secondary network, I can see the outgoing (redundant) connection correctly since the listener is also on the secondary network. But as the entity only receives a stream on the primary network, the Hive marks the incoming stream as offline (it cannot see the talker since the talker is not on the secondary network). This tempted me to click the offline stream to remove it, but that disconnected a perfectly healthy stream on the primary network.

I would suggest to either rename "Offline Streams" to "Talker not available", or to add another row below "Offline Streams>" that indicates a healthy stream on the other interface / whose talker is not on the current interface.

**Comment by christophe-calmejane** [comment]
Hi,

I'm not sure to understand your setup correctly.
If your devices are not confidential, could you use the **File/Export/Full Network State** feature and attach the file here?
If it is confidential, you can use the shift key when exporting so it's in text format (and you can edit/hide whatever information you want).
Thanks.

**Comment by scrmea** [comment]
Hi,
I'll do that once I have the same setup running again. But it's not that complex:

Device 1 has only a primary interface.
Device 2 has a primary and a secondary interface.

Controller on primary connects stream from Device 1 to Device 2 primary interface.
Hive on secondary network does not see Device 1.
Hive on secondary network shows an offline stream for Device 2 redundant input stream. But that stream is not offline, it's up and running. It's just exclusive to the primary network.

**Comment by christophe-calmejane** [comment]
This is a known limitation of the current Milan/AVDECC specs that will be addressed in a future revision.
In the meantime it is stronglt recommended to connect controllers to the primary interface, if you mix redundant and non-redundant devices.

It's not an easy task to detect if a stream is running or not for various reasons, even more difficult to properly display (with the current code base) real offline streams and running streams from unknown talkers.
Something that can be done though, is show a popup when trying to disconnect a connection from a listener that is *media locked* if the device is Milan compatible.
