### ISSUE TITLE
crash when selecting input/output stream descriptor in entity inspector (segfault)

### ISSUE THREAD

**Issue by mrklkrl** [christophe-calmejane/Hive#105]
Hive version: 1.3.0 beta 1
computer: late 2013 27” iMac (intel i7)
OS: MacOS Catalina 10.15.7
Peripherals: RME Digiface AVB (firmware 1.0.219)

repro steps:

1) select the RME in the entity model inspector. 
2) click on any input or output stream descriptor
3) crash occurs 100% of the time

**Comment by mrklkrl** [comment]
When exporting the full network state, the following error appears: Export failed:
Invalid AudioCluster Descriptor Index: 8 but expected 0 
![export network state error](https://user-images.githubusercontent.com/19501019/130095776-32f0d079-506e-4aa9-ac70-a446fa4ba62d.png)

**Comment by mrklkrl** [comment]
This bug also occurs with the iMac as a virtual entity. It happens regardless of wether i'm using the native apple avdecc library or pcap.

**Comment by christophe-calmejane** [comment]
Does the crash occur with 1.2.6 also?

Regarding the export failure, it's because the entity does not have a valid model (as per IEEE1722.1).

**Comment by mrklkrl** [comment]
> Does the crash occur with 1.2.6 also?
> 
No, it does not.

**Comment by christophe-calmejane** [comment]
Ok great it means it's already fixed then 😜

**Comment by mrklkrl** [comment]
Ah. The version numbers led me to believe 1.3 is newer than 1.26.

**Comment by christophe-calmejane** [comment]
Kind of :)
1.3 is a private branch for AVnu only so it might be a bit older than public release.
I'll have to check next week but I'm pretty sure there is a newer 1.3.x (Check on slack maybe)

**Comment by christophe-calmejane** [comment]
So I checked, 1.3.0 beta2 was released Jun 29th, fixing that exact issue. Grab the latest version from Slack ;)
