### ISSUE TITLE
error in README.md

### ISSUE THREAD

**Issue by acollaborator** [christophe-calmejane/Hive#119]
These directions in README.cmd for Linux compilation do not work.
"pass the following option to gen_cmake.sh: -qt5dir /usr/lib/x86_64-linux-gnu/cmake/Qt5/"

Using "-qt5dir /usr/lib/x86_64-linux-gnu/cmake" does work
because 
https://github.com/christophe-calmejane/Hive/blob/main/gen_cmake.sh:
	# Validate QtDir
	if [ ! -f "${QtDir}/Qt${QtMajorVersion}/${QtConfigFileName}" ]; then
		echo "Invalid Qt folder (${QtDir}): ${QtConfigFileName} not found in the folder."
		echo "Maybe try the -qtdir option, see help (-h)"
		exit 1
	fi

**Comment by christophe-calmejane** [comment]
Thanks for finding this mistake, the instructions for linux were not updated when Qt6 support was added.
