### ISSUE TITLE
Linux compile fails

### ISSUE THREAD

**Issue by acollaborator** [christophe-calmejane/Hive#120]
gen_cmake.sh exits with errors in my Linux environment.  Perhaps the issue is with my environment.  

Can anyone else currently build Hive for Linux?

Is there a better place to discuss troubleshooting compilation of Hive than submitting an issue?

./gen_cmake.sh -qtdir /usr/lib/x86_64-linux-gnu/cmake -qtvers 5.15.2 -release
/--------------------------\
| Generating cmake project
| - GENERATOR: Unix Makefiles
| - PLATFORM: linux
| - ARCH: x64
| - BUILD TYPE: Release
| - QT VERS: 5.15.2
\--------------------------/

-- Appcast URL for Hive Releases defined to: https://localhost/hive/appcast-release.xml
-- Appcast URL for Hive Betas defined to: https://localhost/hive/appcast-beta.xml
-- Appcast fallback URL for Hive Releases defined to: https://localhost/hive/appcast-release.xml
-- Appcast fallback URL for Hive Betas defined to: https://localhost/hive/appcast-beta.xml
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CU_PROJECT_URLABOUTINFO not set, using default value: https://github.com/christophe-calmejane/Hive
-- CU_BETA_TAG not set, using default value: -beta
-- Version: 6.1.2
-- Build type: Release
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Using the single-header code from /home/thedude/github/hive/Hive/3rdparty/avdecc/externals/3rdparty/json/single_include/
CMake Error: File /home/thedude/github/hive/Hive/3rdparty/avdecc/externals/3rdparty/json/cmake/config.cmake.in does not exist.
CMake Error at 3rdparty/avdecc/externals/3rdparty/json/CMakeLists.txt:89 (configure_file):
  configure_file Problem configuring file

-- Building Network Interface Helper Library
-- Building Avdecc library
-- Building Avdecc Controller library
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for pwd.h
-- Looking for pwd.h - found
-- Looking for alloca.h
-- Looking for alloca.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Looking for bzero
-- Looking for bzero - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for _stricmp
-- Looking for _stricmp - not found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for _strnicmp
-- Looking for _strnicmp - not found
-- Looking for random
-- Looking for random - found
-- Looking for srandom
-- Looking for srandom - found
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for basename
-- Looking for basename - found
-- Looking for fchdir
-- Looking for fchdir - found
-- Looking for S_ISCHR
-- Looking for S_ISCHR - found
-- Looking for S_ISFIFO
-- Looking for S_ISFIFO - found
-- Looking for S_ISSOCK
-- Looking for S_ISSOCK - found
-- Building Hive tests
-- Found PythonInterp: /usr/bin/python3.9 (found version &quot;3.9.7&quot;) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also &quot;/home/thedude/github/hive/Hive/_build_linux_x64_makefiles_release/CMakeFiles/CMakeOutput.log&quot;.
See also &quot;/home/thedude/github/hive/Hive/_build_linux_x64_makefiles_release/CMakeFiles/CMakeError.log&quot;.

Something went wrong, check log

[CMakeError.log](https://github.com/christophe-calmejane/Hive/files/8234574/CMakeError.log)
[CMakeOutput.log](https://github.com/christophe-calmejane/Hive/files/8234576/CMakeOutput.log)
[CMakeError.log](https://github.com/christophe-calmejane/Hive/files/8235488/CMakeError.log)
[CMakeOutput.log](https://github.com/christophe-calmejane/Hive/files/8235490/CMakeOutput.log)

**Comment by christophe-calmejane** [comment]
Hi,

I just compiled fine on Linux Ubuntu.
Looks like you are missing a file in a 3rd party, are you sure you correctly retrieved all submodules? Is the 3rdparty/avdecc/externals/3rdparty/json/cmake/config.cmake.in file present on your system?

**Comment by acollaborator** [comment]
./Hive/3rdparty/avdecc/externals/3rdparty/json/cmake/config.cmake.in is not present. 

I am not sure how to validate that all submodules were correctly retrieved. setup_fresh_env.sh completed with no error messages.

My actions were:
1. git clone https://github.com/christophe-calmejane/Hive.git

2. cd ./Hive

3. cp .hive_config.sample .hive_config

4. # I did not change .hive_config. I did not notice that any changes were needed for building Hive for Linux.

5. ./setup_fresh_env.sh

6. ./gen_cmake.sh -qtdir /usr/lib/x86_64-linux-gnu/cmake -qtvers 5.15.2 -release

7. # The result was the errors reported for this issue.

I will try erasing and starting over again.

**Comment by acollaborator** [comment]
Sigh, operator error I guess. gen_cmake.sh completes now after I deleted and re-cloned the repository today.

But make fails with :
In file included from /home/sonnet/github/Hive/3rdparty/avdecc/src/protocolInterface/protocolInterface_pcap.cpp:33:
/home/sonnet/github/Hive/3rdparty/avdecc/src/protocolInterface/pcapInterface.hpp:28:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/build.make:316: 3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/protocolInterface/protocolInterface_pcap.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1381: 3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by acollaborator** [comment]
Sigh, operator error I guess. gen_cmake.sh completes now after I deleted and re-cloned the repository today.

But make fails with :

In file included from /home/thedude/github/Hive/3rdparty/avdecc/src/protocolInterface/protocolInterface_pcap.cpp:33:
/home/thedude/github/Hive/3rdparty/avdecc/src/protocolInterface/pcapInterface.hpp:28:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/build.make:316: 3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/protocolInterface/protocolInterface_pcap.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1381: 3rdparty/avdecc/src/CMakeFiles/la_avdecc_cxx.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by acollaborator** [comment]
My environment is a new install of Ubuntu 21.10 (Impish Indri) that only contains the libpcap0.8 system library.

Compilation of Hive requires the libpcap0.8-dev development library.

sudo apt install libpcap0.8-dev 

Suggestion:   edit Hive/README.md to describe that compilation with Linux requires the libpcap-dev package.

Christophe, thank you for maintaining Hive.

**Comment by christophe-calmejane** [comment]
Well, instructions are actually already there... just not in the correct file (sort of).
Hive depends on AVDECC, and AVDECC instruct to install pcap-dev.
What is missing is a link from Hive to AVDECC in the required setup :)
I'll fix that, thanks again for testing from scratch, the more people are trying to compile, the more cases we'll cover.
