### ISSUE TITLE
building Hive with Unbuntu 20.04

### ISSUE THREAD

**Issue by acollaborator** [christophe-calmejane/Hive#121]
I am having trouble building Hive to run with with Ubuntu 20.04. I am opening this issue to share my path to a solution.

Ubuntu 20.04 is dependent on Qt 5.12.8, so I used Qt installer to install Qt 5.15.2 in my home directory.
I downloaded the Qt installer from https://www.qt.io/download-qt-installer

Then I exported the following environment variables before building Hive.

LD_LIBRARY_PATH=/home/thedude/Qt/5.15.2/gcc_64/lib
QTDIR=/home/thedude/Qt/5.15.2/gcc_64
QT_BASE_DIR=/home/thedude/Qt/5.15.2/gcc_64
QT_BASE_PATH=/home/thedude/Qt
PATH=/home/thedude/Qt/5.15.2/gcc_64/lib:/home/thedude/Qt/5.15.2/gcc_64/bin:$PATH
PKG_CONFIG_PATH=/home/thedude/Qt/5.15.2/gcc_64/lib/pkgconfig

./gen_cmake.sh -qtdir /home/thedude/Qt/5.15.2/gcc_64/lib/cmake -qtvers 5.15.2 -release
and make run to completion.

But after I run
sudo setcap cap_net_raw+ep /home/thedude/github/Hive/_build_linux_x64_makefiles_release/src/Hive
this Hive runtime error is occurs
./Hive: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./Hive)

I do not understand why Hive is referencing a shared library path of  /lib/x86_64-linux-gnu/ 
The shell from which Hive is launched has the environment variables I listed above.

qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /home/thedude/Qt/5.15.2/gcc_64/lib

**Comment by christophe-calmejane** [comment]
You should not export any variables before building as it might mix develop and runtime libs.
`gen_cmake` is supposed to handle everything for you, if you only provide the `-qtdir` and `-qtvers` parameters.

Well, at least it was supposed to work a couple months ago :)
I'll try to build it again using Qt intaller if I can find some time.

**Comment by acollaborator** [comment]
I removed the shell variables and deleted and re-cloned the Hive repository and ran 
./gen_cmake.sh -qtdir /home/thedude/Qt/5.15.2/gcc_64/lib/cmake -qtvers 5.15.2 -release

The result was the same -
"Hive starts running when 'setcap' is not run or is removed; the Hive GUI displays and functions. As expected though, I cannot see any AVDECC entities. But after running 'setcap' , the runtime error immediately occurs when Hive is launched. No GUI ever appears.
./Hive: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./Hive)"

I will continue searching through Qt forums.

**Comment by acollaborator** [comment]
A-ha!    Hive runs after doing the following: 

After reading https://www.linuxfromscratch.org/blfs/view/svn/x/qt5.html , 
I learned to add a file to /etc/ld.so.conf.d/ and run ldconfig.

/etc/ld.so.conf.d/Qt_5.15.2.conf:
# Begin Qt addition
/home/thedude/Qt/5.15.2/gcc_64/lib
# End Qt addition

Then run:
sudo ldconfig

**Comment by christophe-calmejane** [comment]
You could also add "." (or the full path) to your LD_LIBRARY_PATH env variable, which is a less global way (user specific) of adding a LD path to your shell. Either solution will work.
When I said _don't export any variables_, I was mentioning the _build process_, not the _runtime_ :)

Glad you sorted this out, your information might but helpful to other people, thanks.
