### ISSUE TITLE
Each entity configuration shows currently selected configuration description

### ISSUE THREAD

**Issue by romansavrulin** [christophe-calmejane/Hive#123]
Affected versions: v1.2.7, v1.2.8-beta6

I believe it should look like this
<img width="519" alt="image" src="https://user-images.githubusercontent.com/1313542/164991015-e014aa1d-2c2a-4ba2-b47e-24b7931037a3.png">

But in Hive it duplicates currently selected configuration
![image](https://user-images.githubusercontent.com/1313542/164990957-e5940655-298d-4433-92c3-0aa166b65adb.png)
![image](https://user-images.githubusercontent.com/1313542/164990972-0b6615d1-5f88-41c8-a9f3-e0b4a07d8edb.png)

**Comment by christophe-calmejane** [comment]
Interesting, thank you, I'll take a look at it.

**Comment by christophe-calmejane** [comment]
Thanks for the report, unfortunately the issue is coming from macOS.
I double checked with wireshark what Hive receives from macOS, and it seems to be receiving the exact same `READ_DESCRIPTOR` response whatever `descriptor_index` is being used during the query.

**Comment by christophe-calmejane** [comment]
What macOS version are you using?
I reproduced using Big Sur.

**Comment by christophe-calmejane** [comment]
So, after further investigation, it seems to actually be a Hive issue, thanks for finding it.
