### ISSUE TITLE
Device not compilant

### ISSUE THREAD

**Issue by davigodoy** [christophe-calmejane/Hive#147]
When I connect my device the program detects but shows the error 

[0x000a92fffe02a90e] EntityModelID is expected to be identical in ADP and ENTITY_DESCRIPTOR

So I can´t work on that.

**Comment by christophe-calmejane** [comment]
Hi,

I will need more info in order to give you a proper answer:

* Which device?
* Which manufacturer?
* Which version of Hive?

Thank you

**Comment by davigodoy** [comment]
StudioLive 32R from Presonus.
EntityID 0x000A92E001080601
I´m using Hive 1.2.9 32bits for windows.

**Comment by davigodoy** [comment]
![HIVE](https://user-images.githubusercontent.com/17010/216361445-3c6b1baa-4854-478f-ba7b-b2f39a0ce8f3.png)

**Comment by christophe-calmejane** [comment]
Ok it simply means that this device is not IEEE1722.1 compliant, it's sending contradictory information.
The `entity_model_id` field found in the `ENTITY` descriptor must be the same than advertised in the ADP broadcast message.

See this from the specification:
![image](https://user-images.githubusercontent.com/23314088/216366332-00b31325-94c6-4610-861b-ae8557575534.png)

**Comment by davigodoy** [comment]
So, how can I use the HIVE to patch channels? Or the device has a problem that avoid this?

**Comment by christophe-calmejane** [comment]
I'm not sure what you actually want to achieve.
The device being flagged as non-1722.1 compliant should only disable Milan features. You should still be able to connect streams, change stream formats, change dynamic mappings, etc

**Comment by davigodoy** [comment]
So, I want to get the audio from AVB from the device. But the option to mapping is disabled.
In Windows, how can I get the sound to my DAW?

**Comment by davigodoy** [comment]
I got it!
Thanks!

**Comment by christophe-calmejane** [comment]
Thanks for the warning report on the device, I'll try to notify the editor.
