### ISSUE TITLE
possibility to modify the presentation time of each stream

### ISSUE THREAD

**Issue by JohanHuge** [christophe-calmejane/Hive#151]
Add an editable parameter to modify the presentation time of each output stream between 0 and 2ms.

**Comment by christophe-calmejane** [comment]
Add a combobox from 0.25 to 3.00, every 0.25m

**Comment by max24192** [comment]
That would only work for 48 kHz (and multiples) as 250 us is the duration of 12 samples at that sampling rate. However, if using those offsets at 44.1 (and multiples) and syncing to that stream, the listeners have a phase offset of their media clock. IMHO PTOs should always be set in full multiples of a sample duration.

**Comment by christophe-calmejane** [comment]
I just need to start with something quick and easy to implement. It would still "work" since you can always choose the upper value, doesn't it? Anyway it would still be better than the current UI that is much more limited (and bugged).

**Comment by max24192** [comment]
Understood. Yes, if a stream is configured with a PTO of [623600ns](https://docs.rme-audio.com/12mic/030-5c_avb_latency/), you could show and highlight 0.75ms, and when there is no change to the value by the user, you could leave it as is. It is also possible to just make the field a numeric input field with 100ns granularity to allow manual MTT 'tuning' (minimum latency according to actual stream transit time), but admittedly that may be less convenient for the majority of users.
