### ISSUE TITLE
Mac OS Ventura entities not visible

### ISSUE THREAD

**Issue by arturas1987** [christophe-calmejane/Hive#153]
Hive 1.3.0-beta5 cannot see Venturas's entity.  Possibly due to ATDEC control instead AVDEC. When are you planning to add this missing function?

**Comment by arturas1987** [comment]
<img width="694" alt="Screenshot 2023-06-24 at 20 10 06" src="https://github.com/christophe-calmejane/Hive/assets/28387311/65dc384a-ddbc-4c69-a67b-b27873d86687">

**Comment by christophe-calmejane** [comment]
Hi,
there is no issue regarding Ventura's entity, it's still visible and usable from Hive.
But if you are using Hive on Ventura and you want to interact with the entity on the same computer, you _must_ use `MacOS Native` protocol (from Hive's settings) or you won't be able to properly detect the entity.
