### ISSUE TITLE
Incorrect capitalization in includes

### ISSUE THREAD

**Issue by Florob** [christophe-calmejane/Hive#158]
Commented on #157 a bit prematurely.
There are multiple cases where includes have incorrect capitalization causing compilation failures on case-sensitive file systems:

`VirtualController.hpp` → `virtualController.hpp`:
* `libs/modelsLibrary/controllerManager.cpp`
* `libs/modelsLibrary/virtualController.cpp`

`qtMate/` → `QtMate/`:
* `src/counters/streamInputCountersTreeWidgetItem.cpp`
* `src/diagnostics/controlDiagnosticsTreeWidgetItem.cpp`
* `src/diagnostics/entityDiagnosticsTreeWidgetItem.cpp`
* `src/diagnostics/streamInputDiagnosticsTreeWidgetItem.cpp`
* `src/nodeTreeDynamicWidgets/streamDynamicTreeWidgetItem.cpp`
* `src/statistics/entityStatisticsTreeWidgetItem.cpp`

**Comment by christophe-calmejane** [comment]
I don't understand how this was not caught when I closed #157 as I compiled on a case sensitive system before closing the issue. Something is weird.
