### ISSUE TITLE
Can't open dynamic mappings editor from Entity Model Inspector

### ISSUE THREAD

**Issue by Florob** [christophe-calmejane/Hive#159]
Clicking the 'Edit' button on STREAM_PORT_INPUT/OUTPUT descriptors in the Entity Model Inspector doesn't do anything anymore.
I bisected this to d33f4df9d337f437e652c4673c8a84a9c1df6fd0. And indeed opening the editor from the matrix shows all stream ports now, but editing individual ones appears to be broken.

**Comment by Florob** [comment]
Potentially relatedly the assert https://github.com/christophe-calmejane/Hive/blob/e80e4fe5115febc6a253643c2535cd7b4c2d518d/src/nodeTreeDynamicWidgets/streamPortDynamicTreeWidgetItem.cpp#L45 introduces in that commit fires whenever selecting a STREAM_PORT.

**Comment by christophe-calmejane** [comment]
Working fine for all my test devices.
I need a dump of a non-working device.

**Comment by Florob** [comment]
That is strange. It doesn't work for all my test devices, and it doesn't work with the test data in the repository (`tests/data/connectionMatrix/1-Normal_Normal-ConnectedNoError_WrongFormat.json` is the one I tried).
Maybe there is some other strange different between our setups?

Still here is an RME M-1610 for reference (gziped, because github wouldn't accept it otherwise):
[EntityModel_0x480BB2FFFED70403.gz](https://github.com/christophe-calmejane/Hive/files/12780827/EntityModel_0x480BB2FFFED70403.gz)

**Comment by christophe-calmejane** [comment]
`tests/data/connectionMatrix/1-Normal_Normal-ConnectedNoError_WrongFormat.json` is working perfectly fine on my `windows` computer. I'll try macOS when I get a chance, but I suppose you are using `linux` and I don't have any working linux right now, may be the difference.

**Comment by christophe-calmejane** [comment]
ok so I managed to use the linux docker image (from the repo) and load `1-Normal_Normal-ConnectedNoError_WrongFormat` (converted to `.ans` first), and I don't have any issue opening the mappings editor from the STREAM_PORT_INPUT descriptor.
![image](https://github.com/christophe-calmejane/Hive/assets/23314088/ac73ac33-ac57-4e39-9de5-7b4e1fc5bc8a)

So, I have no idea what is wrong with your setup. I'll try to gather other users input though, just in case.

**Comment by Florob** [comment]
I've had someone else compile and run Hive on their system on Saturday, which is when I originally encountered this. That was Fedora, while I'm using Arch. So it's not even just my system… This is Qt 6.5.3, but at least for the assert firing I don't see how that could make a difference.

Any logs I could add to try and determine why `audioUnitIndex` is not being set?

**Comment by Florob** [comment]
Got it (sort of). If you highlight the parent AUDIO_UNIT before selecting the STREAM_PORT_* things work. If you just expand the AUDIO_UNIT, but never highlight it, before selecting the STREAM_PORT_* the behaviors described above occur.

**Comment by christophe-calmejane** [comment]
Ok I see, and I understand now, thanks
