### ISSUE TITLE
Installer: NSIS /S flag still has a popup even if winpcap is installed

### ISSUE THREAD

**Issue by reuterng** [christophe-calmejane/Hive#164]
### Behavior: 

WinPcap installer is still run by the Hive installer even when WinPcap is already installed and the NSIS built-in silent flag is invoked.

WinPcap does not allow silent installations, as the devs for that project moved that functionality into the paid winpcap library.

If you run the installer for Hive with the /S "silent" flag, the user is presented with a popup asking if they want to force the WinPcap installation or cancel the WinPcap Installation. See attached Screenshot

#### Request:
Make it so the /S flag skips the winpcap installation if WinPcap is already installed **or** add a "No winpcap" switch for  the installer

Unfortunately, there is no way to silently install winpcap, but we should be able to install hive without calling the winpcap installer if it is not needed.

Thanks

![image](https://github.com/christophe-calmejane/Hive/assets/16762605/5105d670-8ff9-4eb6-aa13-6778d35b8da6)

**Comment by christophe-calmejane** [comment]
Hi, try `/NOPCAP` along with `/S`
