### ISSUE TITLE
Find something more lightweight than QtWebEngine to display the Changelog

### ISSUE THREAD

**Issue by christophe-calmejane** [christophe-calmejane/Hive#21]
We use a very small subset of markdown, so maybe it's easy to write our own small C++ parser, and give the generated string to QLabel

**Comment by christophe-calmejane** [comment]
http://www.pell.portland.or.us/~orc/Code/markdown/ looks like a very good candidate

**Comment by epebble** [comment]
https://github.com/vmg/sundown seems pretty nift

**Comment by christophe-calmejane** [comment]
Or https://github.com/mity/md4c

**Comment by christophe-calmejane** [comment]
Fixed in b8b472fce00f0bc244e43fc20ab15514f0ec6c9f
