### ISSUE TITLE
Image download uses maximum_length instead of length

### ISSUE THREAD

**Issue by fHarmuth** [christophe-calmejane/Hive#27]
The image download triggered by downloadImage() in entityLogoCache.cpp uses for its call to manager.readDeviceMemory() the static parameter model->maximumLength. The dynamic parameter length should be used instead because it contains the actual size of the data contained in the memory region (see 7.2.10 MEMORY_OBJECT Descriptor for details).

**Comment by christophe-calmejane** [comment]
Fixed in 508b23162701fe20e3357321e5596cccd5683006
