### ISSUE TITLE
connecting redundant streams wierdness

### ISSUE THREAD

**Issue by graffiti** [christophe-calmejane/Hive#34]
looks like a regression between 1.0.6 and 1.0.7, this was working in 1.0.6 but in 1.0.7 I can connect a talker redundant stream output 0 to a listener redundant stream input 0 or 1, but trying to connect talker redundant stream output 0 to a listener redundant stream input 2 or 3 fails 'curiously'. Clicking the x-point for input stream 2 does nothing (no ACMP packets sent), and clicking the x-point for input stream 3 causes input stream 2 to connect!
Difficult to explain, I have send Christophe a video but I can't post it publicly.

**Comment by christophe-calmejane** [comment]
Duplicate (or vice versa :) ) of #35
