### ISSUE TITLE
Support for npcap

### ISSUE THREAD

**Issue by christophe-calmejane** [christophe-calmejane/Hive#65]
Add automatic detection for npcap, if installed on the system

**Comment by christophe-calmejane** [comment]
https://github.com/hsluoyz/WinDump/commit/dffe2eaa520fc3b449ec0a90dcfa24f96359bbfa

**Comment by christophe-calmejane** [comment]
Also check http://www.win10pcap.org/

**Comment by christophe-calmejane** [comment]
Tried to support win10pcap (interface names are identical to what's returned by networkInterfacesHelper), but every packet sent causes errors in the driver: FATAL bad memory block.

**Comment by christophe-calmejane** [comment]
Hive prints a warning in case winPcap is not installed (but npcap is), although it's working perfectly. This should be addressed.

**Comment by Rygle** [comment]
winpcap has ceased development and its webpage recommends using npcap and states that there are several issues with using it.

"The WinPcap project has ceased development and WinPcap and WinDump are no longer maintained. WE RECOMMEND USING [Npcap INSTEAD](https://nmap.org/npcap/).

If you do insist upon using WinPcap, be aware that its installer

- Uses [NDIS 5.0](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/overview-of-ndis-versions), which might not work well with newer versions of Windows.
- Was built with an [old version of NSIS](https://sourceforge.net/p/nsis/news/) and as a result is vulnerable to [DLL hijacking](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13573)."

From https://www.winpcap.org/install/default.htm

**Comment by christophe-calmejane** [comment]
AFAIK, WinPCap on it's own is not a security or stability issue, only the installer part of it.

Maybe it's not such a security issue (didn't check the chinese security post) since Hive installer is directly calling winpcap installer, so it's possible that you cannot DLL-inject in such a case (didn't think about it more deeply).

Regarding the driver itself I don't see microsoft dropping NDIS5 support any time soon, so I think we are still safe for a few years.

Now, regarding npcap, the issue is that embedding its installer is not allowed that easily, the alternative been forcing the users to manually install it (which is not that great when you automate things).
Current Hive version does support npcap (if manually installed), but only in _winpcap compatible mode_, and it will print an unjustified warning (until fixed), but if you are really concerned about security, that's an option (just don't install winpcap during Hive installation).

Nevertheless I'll try to fix the warning and fully support npcap (non-compatible mode) when I get a chance. Embedding it is another story though.

**Comment by christophe-calmejane** [comment]
A fix for the popup has been implemented and will be pushed for next version. Hive will then try to use _npcap_ before _winpcap_ if both are installed.

Embedding (or forwarding) _npcap installer_ will be addressed later, **if possible**.

**Comment by christophe-calmejane** [comment]
Having issues with `npcap` when `winpcap` is also installed.
This is causing unexpected behavior for entities on the same computer than Hive (entities are blinking online/offline), see technical explanation here: https://github.com/nmap/npcap/issues/285
