### ISSUE TITLE
[Ubuntu build] fatal error: abstracttreeitem.hpp: No such file or directory

### ISSUE THREAD

**Issue by nclman** [christophe-calmejane/Hive#74]
Hi, I noticed some cases here where build errors occur (on Linux systems) due to upper/lower case mismatches.

In this case, "abstracttreeitem.hpp" should actually be "abstractTreeItem.hpp".

**Comment by christophe-calmejane** [comment]
Thanks for the report, will check that

**Comment by christophe-calmejane** [comment]
This was already fixed, thanks for the report
