### ISSUE TITLE
Add a button to acknowledge all error counters in all discovered entities

### ISSUE THREAD

**Issue by christophe-calmejane** [christophe-calmejane/Hive#77]

**Comment by BenjaminLandrotLAcoustics** [comment]
I wanted to ask for this improvement, and notice the issue already exists. Up!

**Comment by BenjaminLandrotLAcoustics** [comment]
I would suggest a new button in the toolbar

**Comment by christophe-calmejane** [comment]
Any suggestion for the toolbar icon (possibly from google's material icons)?

**Comment by BenjaminLandrotLAcoustics** [comment]
Icon suggestions:

https://fonts.google.com/icons?selected=Material%20Icons%3Asettings_backup_restore%3A
https://fonts.google.com/icons?selected=Material%20Icons%3Acancel_presentation%3A
https://fonts.google.com/icons?selected=Material%20Icons%3Adeselect%3A
https://fonts.google.com/icons?selected=Material%20Icons%3Acleaning_services%3A

**Comment by christophe-calmejane** [comment]
_deselect_ would actually be perfect for #107

**Comment by christophe-calmejane** [comment]
We also have the possibility to create our own glyph (we now have our own font), maybe something like https://fonts.google.com/icons?selected=Material+Icons:report_gmailerrorred: or https://fonts.google.com/icons?selected=Material+Icons:warning_amber: with a backslash overlay?

**Comment by BenjaminLandrotLAcoustics** [comment]
Yes. I like the idea of the broomstick which clearly shows that we want to start fresh and get rid of the past.

**Comment by christophe-calmejane** [comment]
I guess we might also add a mini-toolbar directly in the (now dockable) entities list view, along with a filter. Like the logger view actually. That way it would be more clear the clear icon/action is related to that list.
