### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by elabbing** [christophe-calmejane/Hive#80]
Hi, I try to compile on my host PC:
_Linux ubuntu 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux_

I installed
gcc 7.4 by default Bionic installation
gcc 8.3
 QT 5.12.4
 Cmake 3.13 in /Hive/cmake

I run
```
./setup_fresh_env.sh
./gen_cmake.sh
```
then go in my build directory and did
`make all`
but I'm having following error:
```

[ 91%] Built target Hive_static
make[2]: ***  No rule to generate target "../resources/dsa_pub.pem", needed for "src/Hive_autogen/7BV4YJK25R/qrc_main.cpp".  Stop.
CMakeFiles/Makefile2:1320: recipe for target 'src/CMakeFiles/Hive.dir/all' failed
make[1]: *** [src/CMakeFiles/Hive.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Please, could give me any hints to resolve?
Thanks a lot

**Comment by christophe-calmejane** [comment]
Hi,
sorry I was away for a few days, I'll take a look at this as it was building without errors on my raspberry build machine. Maybe I forgot to push some files :D

**Comment by elabbing** [comment]
Hi, thanks for your reply.
I solve putting a dummy file
`dsa_pub.pem`
for DEBUG compiling.

Anyway, I try to compile with RELEASE option and
I'm getting following when I do `make` in my build directory:
/```
home/iemai/Documents/Hive/src/connectionMatrix/model.cpp: In member function ‘virtual QVariant connectionMatrix::Model::data(const QModelIndex&, int) const’:
/home/iemai/Documenti/Hive/src/connectionMatrix/model.cpp:2990:41: error: unused parameter ‘index’ [-Werror=unused-parameter]
 QVariant Model::data(QModelIndex const& index, int role) const
                      ~~~~~~~~~~~~~~~~~~~^~~~~
/home/iemai/Documents/Hive/src/connectionMatrix/model.cpp:2990:52: error: unused parameter ‘role’ [-Werror=unused-parameter]
 QVariant Model::data(QModelIndex const& index, int role) const
                                                ~~~~^~~~
cc1plus: all warnings being treated as errors
src/CMakeFiles/Hive_static.dir/build.make:205: recipe for target 'src/CMakeFiles/Hive_static.dir/connectionMatrix/model.cpp.o' failed
make[2]: *** [src/CMakeFiles/Hive_static.dir/connectionMatrix/model.cpp.o] Error 1
CMakeFiles/Makefile2:1360: recipe for target 'src/CMakeFiles/Hive_static.dir/all' failed
make[1]: *** [src/CMakeFiles/Hive_static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

A little thing: after first run, splash screen to choose basic or developer usage is not anymore displyed..

Could you help me, please?

**Comment by christophe-calmejane** [comment]
About your first reported issue, there is a copy/paste mistake in setup_fresh_env.sh line 285.
It should be `elif [[ $osName == "linux" ]];`

**Comment by christophe-calmejane** [comment]
I've fixed the compilation issues, but I cannot push it yet.
Here is the diff:
```
diff --git a/src/connectionMatrix/model.cpp b/src/connectionMatrix/model.cpp
index db24ed7..796ea39 100644
--- a/src/connectionMatrix/model.cpp
+++ b/src/connectionMatrix/model.cpp
@@ -2987,7 +2987,7 @@ int Model::columnCount(QModelIndex const&) const
        }
 }

-QVariant Model::data(QModelIndex const& index, int role) const
+QVariant Model::data([[maybe_unused]] QModelIndex const& index, [[maybe_unused]] int role) const

```
