### ISSUE TITLE
Sort entities list by column

### ISSUE THREAD

**Issue by BenjaminLandrotLAcoustics** [christophe-calmejane/Hive#81]
Enhancement/UI
Add possibility to alphanumerically sort the entities list by any column (especially the 'Name' column).

Sorting by column is done by clicking once on the chosen column, ascending order.
Clicking again on a column already used for sorting reverses the sorting order (ascending/descending).

Sorting is applied to entities list as well as to connections matrix, to keep visual consistency between both.

**Comment by christophe-calmejane** [comment]
Sortable columns:

- Compat
- EntityID
- Name
- Group
- GrandmasterID
- MediaClock MasterID
- MediaClock MasterName

**Comment by BenjaminLandrotLAcoustics** [comment]
Checked 1.2.5-beta1. Sorting works fine in the entities table view.

However, the sorting of the entities in the table view is not mirrored to the Connection Matrix.
Sorting by one column in the table view should also sort entities the same way in Talkers and Listeners lists in the Connection Matrix.
This sorting synchronization may be enabled or disabled as a user setting in preferences.

**Comment by christophe-calmejane** [comment]
@envt is it feasible easily?
