### ISSUE TITLE
macOS 10.14 cannot load PCap (started with Hive 1.2.2-Beta3)

### ISSUE THREAD

**Issue by christophe-calmejane** [christophe-calmejane/Hive#86]
I have tried the homebrew fix, however it does not fix the problem / the beta does not work on my 10.4.6.. (most likely because brew doesn't symlink to /usr/local/opt/libpcap/bin). 
Is there a way I can manually set the access rights?

_Originally posted by @m2lab in https://github.com/christophe-calmejane/Hive/issues/79#issuecomment-604759393_

**Comment by christophe-calmejane** [comment]
@m2lab Thanks to your help on the other issue (#79) I think I found the solution.
I'll make a new beta version today so you can confirm it's fixed).

**Comment by christophe-calmejane** [comment]
Should be fixed in dea0e4c63b9cbdd53121592e8d318ad873e3c8be (and Beta 1.2.2-5)

**Comment by m2lab** [comment]
Confirmed, it is fixed. Thank you!
