### ISSUE TITLE
Configured MAC not recognized (but works on AVDECC)

### ISSUE THREAD

**Issue by ErmannoBonifazi** [christophe-calmejane/Hive#91]
I have a Mac configured as AVB device that work great in AVDECC utility but is not recognized (or at least have empty description in HIVE) and is totally missing from the connection Matrix.
![Screen Shot 2020-06-08 at 22 54 31](https://user-images.githubusercontent.com/66646455/84079727-53f94b00-a9db-11ea-902c-09228bd4abd2.png)
![Screen Shot 2020-06-08 at 22 54 56](https://user-images.githubusercontent.com/66646455/84079735-56f43b80-a9db-11ea-8cb6-cdc9615766d2.png)

**Comment by christophe-calmejane** [comment]
Hi,

if you are running Hive from said Mac, then you have to change the *ProtocolInterface* used to communicate with the network. Try switching to *MacOS Native* in the settings menu.

**Comment by ErmannoBonifazi** [comment]
Thank you for the note.
Work like a charm.
Compliment for the tool.

EB
